### ISSUE TITLE
Floating metamark and notes issues

### ISSUE THREAD

**Issue by justindlivingstone** [livingstoneonline/Missionary-Travels#1]
I'm having problems with the second-metamark (i.e. having two metamarks side by side in the margin) and alternate-metamark xslt (i.e. having a note and a metamark side by side in the margin). For some reason, in liv_000099_0092_TEI, a couple of paragraphs are being identified as 'second-metamark' and 'alternate-metamark' when they shouldn't be, and the format is thus being scrambled.

**Comment by awisnicki** [comment]
I think I've resolved this by using what I noted just before I left: adding [0] in the relevant place
Pull down the new file from Github and let me know if this works. The one I fixed is on page 0097 and see lines 1029-1041 of the XSL file.

**Comment by justindlivingstone** [comment]
I had a look and what this has done is turned off the feature altogether. So the two 'tr' metamarks on 0114 are now on top of each other again instead of side by side, and the note and metamark ('Query collecting' and 'Qy') on 0116 are also on top of each other. I tried various placements of [0] and couldn't get it to work.

**Comment by awisnicki** [comment]
Resync the files and look at the xsl file, line 1043. I think I've fixed it. 0109 looks good as do 0114 and 0116. The issue appears to be that on 0109, near the end of the page, you had an empty metamark @flag with a forward slash at the end so every subsequent line was seen as having a metamark on it and this was making 0110 wonky. So, right now, the new xsl line takes metamarks that are empty and simply turns them off. Once you define things like metamark/@flag we can give that all of a higher priority and then this new line will only catch those that are not specifically addressed in the xsl. Hope that makes sense. I also commented out the lines in the xsl file with issue #2 for now.

**Comment by justindlivingstone** [comment]
That's terrific – thanks for fixing it. It looks perfect to me. I think I understand the 'priority' issue, and in fact I gave it a quick try and was able to get my opening brackets appearing on 'flag' when I gave it a priority of 10 without any problems materialising. Thanks for this. A great step forward.

**Comment by awisnicki** [comment]
Awesome. Closing this ticket. Incidentally, I'd suggest you clean up the metamark text in the xsl file overall (and any other parts of the file you've modified), just so it's easier to find things/implement things going forward.

**Comment by justindlivingstone** [comment]
Adrian, I've reopened this issue. I noticed that all the empty metamarks had been turned off by the line of code you added (i.e. my arrows for 'insertion'; the sign used for 'no-new-paragraph' etc). This may well be dealt with later when we sort out the 'flag' issue and set priorities accordingly. But I thought I'd draw this to your attention in case you thought you'd only turned off 'flag', the metamark that had been distorting several paragraphs. By the way, I've tidied up the code I've added to the xslt.

**Comment by awisnicki** [comment]
You need to rejig the priorities. Right now no metamark display is 10. That should be lower and the metamarks you want to display should get a higher number. The XSLT will process the higher numbers first then whatever is left will be processed next.

**Comment by justindlivingstone** [comment]
This worked. Thanks.

**Comment by awisnicki** [comment]
Brilliant!
