### ISSUE TITLE
Turning on tootips for add and del

### ISSUE THREAD

**Issue by justindlivingstone** [livingstoneonline/Missionary-Travels#11]
Hi Adrian,

We discussed this issue by email, so I'm ticketing it here. I'd like to turn on tooltips for all additions and deletions, so that when you hover over them you get the basic info (hand, colour, and perhaps even place).

I notice that a tooltip currently appears for del, when it is made in the default hand. However, it doesn't seem to show up when there's additional info in the tag (i.e. another hand and another colour).

It would be great if we could try this out - and we can see how the clashes with other tooltips work out. Thanks Adrian.

**Comment by awisnicki** [comment]
Can you point me to a specific file and give me a few examples of additions and deletions to examine? Also an example of what you point out: "I notice that a tooltip currently appears for del, when it is made in the default hand. However, it doesn't seem to show up when there's additional info in the tag (i.e. another hand and another colour)."

**Comment by justindlivingstone** [comment]
No problem! Let's go for file liv_000099_0092 (the first that has additions by unknown hand 3). The first page, 0092, provides enough examples I think

For an example of the tooltip successfully working on del hover over any of the words scored out in black (line 35 'commenced', line 47 'became', and line 48 'related'). In all these cases, there's a tooltip noting 'deletion, type:cancelled'.

Then hover over any of the deletions in red (line 15 'charge of that which, line 21 'the crime is'). In these cases, no tooltip appears.

No tooltip currently appears for any additions:
For a sample addition in DL's hand on 0092, see line 12 'This did not arise' and line 29 'River'. 

For a sample addition in U2's hand, see the page number '86' at the top of the page. See also the name 'Coultart' in line 2 (though it already has a tooltip noting an uncertain reading).

For a sample addition in U3 hand, see any of the words in red. For example line 15 'that crime', line 18 'charged' and line 21 'It is in fact'.

For all these cases, I'd like something similar to the tooltip currently working on del (working for the default hand only). In other words, something like 'deletion, type:cancelled, hand:Unknown Hand 3, rend:red' or 'addition, place:margin left, hand:Unknown Hand 2, rend:gray'.

Thanks for your help with this! It would be pretty cool to get this to work.

**Comment by awisnicki** [comment]
Ok, fixed. This was easy as it was just a matter of adding a specific code to all the examples of del or add in the xsl. 

All the examples you've cited above now work, except "Coultart" which is also correctly working except that the add tag is trumped (yargh! that word again!) by the uncertain tag.

Note: the add code adds "ition" to "add" to produce "addition". The del code adds "etion" to "del" to produce "deletion". (Just FYI if you end up using this code again.)

**Comment by justindlivingstone** [comment]
That's fab! I've checked it and it looks perfect. Really pleased to have that sorted out.

In thanks, I'll promise not to use the word 'trumped' for at least a week...!

**Comment by justindlivingstone** [comment]
Hi Adrian,

Sorry to open this again, but I have a follow up question. You might remember that in volume 3, we added an `"n"` attribute to additions and deletions, when we were working out a way of doing all the colour/hand variants. So there are lots of `n="CL"` and `n="DL"` etc. 

This means that the titles on add and del are also showing this. i.e. "addition, hand: #DL; n: DL; place: above." For an example, you can see on the words 'hawked about' in line 20 on liv_000101_0083.

Is there are way to stop the tooltip title giving the "n" information? If not, I can live with it! I suspect it has something to do with this part of the code:
`<xsl:attribute name="title">
<xsl:value-of select="concat(name(), 'etion, ')"/>
<xsl:for-each select="@*">
<xsl:sort/>
<xsl:if test="not(name()='status')">
<xsl:value-of select="concat(name(),': ', ., '; ')"/>
</xsl:if>
</xsl:for-each>
</xsl:attribute>`

**Comment by awisnicki** [comment]
This one turned out to be easy. 

Basically, you need to find all relevant instances of 

`select="@*"` 

then change them as follows: 

`select="@*[not(name()='n')]"` 

The fix I did fixed "hawked about," so you need to do the others.

**Comment by justindlivingstone** [comment]
Perfect. I've made the changes across the xsl file for vol 3. Thanks Adrian.
