### ISSUE TITLE
hi rend small not working in contents pages

### ISSUE THREAD

**Issue by kilmunbooks** [livingstoneonline/Missionary-Travels#13]
hi rend small is not working in contents pages but is working elsewhere, 0017, 0018, 0019.

**Comment by awisnicki** [comment]
Are you sure? See screen shot. This is clearly a contents page, as labeled at the top, and in looking at the page and in looking at the coding, I see that it's being rendered small.

![screen shot 2017-10-09 at 19 38 38](https://user-images.githubusercontent.com/12518623/31364349-bc501e9c-ad29-11e7-98b8-89329b643658.png)
