### ISSUE TITLE
Spacing between text and tables

### ISSUE THREAD

**Issue by kilmunbooks** [livingstoneonline/Missionary-Travels#15]
Large space between text and tables, but not a consistent amount of space. Only an issue with text about table, not with text below table. Pages 0458 line 3505, 0401 line 3520, 0497 line 3823, 0498 line 3852.

**Comment by awisnicki** [comment]
Fixed all `<table>`s in file by removing `<lb/>` from tables.

**Comment by kilmunbooks** [comment]
Hello,
Are you able to tranform document with the changes you have made? I am unable to transform document as it states` <table>` not allowed here in html. Yet the xml states that the transformation was successful. Please advise.  @awisnicki

**Comment by awisnicki** [comment]
Works for me just fine. Are you transforming the version in the folder called "MT-Master-Files-XML-XSL-CSS"? The version in that folder is the correct one.

**Comment by kilmunbooks** [comment]
Yes that is the one. I synced beforehand could that have upset it?

**Comment by awisnicki** [comment]
Can you take a screen shot of the error you're getting. Also check the folder. If an HTML file is being produced, just double click to open that way.

**Comment by kilmunbooks** [comment]
How bizarre. Clicking on the html is working, the pub ver is opening in firefox. I must have done something to my Oxygen that the screen is not opening directly from the xml when I press ctrl shift T. I profusely apologise for my current bad tech juju. OK I'll get on these now. Thank you Adrian :-)
