### ISSUE TITLE
Justified text

### ISSUE THREAD

**Issue by kilmunbooks** [livingstoneonline/Missionary-Travels#16]
Sometimes the final words in a paragraph are on either side of page, because of following note inside p. Can we use p and p rend="no-indent" to correct, or is that too granular?

**Comment by awisnicki** [comment]
The easiest way to fix this is to add an `<lb/>` before the <note> that follows right after this issue. See screen shot. As far as I can see, this doesn't actually add an extra line of empty space (that's good, i.e., it's not messing up formatting) but it does resolve the issue. I haven't implemented this (you'll need to in all cases), but it's an easy fix.
![screen shot 2017-10-09 at 19 42 23](https://user-images.githubusercontent.com/12518623/31364427-46f52812-ad2a-11e7-8e33-b52ef59c8b4c.png)
![screen shot 2017-10-09 at 19 44 48](https://user-images.githubusercontent.com/12518623/31364475-84820c40-ad2a-11e7-9d2b-abedaa0ced01.png)
![screen shot 2017-10-09 at 19 44 52](https://user-images.githubusercontent.com/12518623/31364476-849e044a-ad2a-11e7-8e4c-9555ed41a689.png)
