### ISSUE TITLE
Small caps in notes

### ISSUE THREAD

**Issue by kilmunbooks** [livingstoneonline/Missionary-Travels#19]
Is it possible to have small caps in notes? See example n=0714 `P<hi rend="smallcaps">YE</hi>`
I've looked at the element and from how I read it 0.9em supercedes everything? Is this right?

**Comment by awisnicki** [comment]
This is now fixed. All instances of small caps throughout (including in all headers) now show as small caps.

**Comment by kilmunbooks** [comment]
Thank you
