### ISSUE TITLE
Metamarks spanning to an anchor tag

### ISSUE THREAD

**Issue by justindlivingstone** [livingstoneonline/Missionary-Travels#2]
I’ve had a go at following James’s instructions for the metamark with a ‘flag’ function in combination with <anchor>. I want an opening bracket (often in red or gray) on the metamark and a closing bracket at the corresponding <anchor> tag. I was able to get an opening bracket appear easily (a triumph!), but can’t get one to appear in the anchor tag. I’m not sure where I’m going wrong. It’s possible that the issue is that there are lots of <anchor> tags, some of which are intended to connect to metamarks with different functions, but from James’s instructions I don’t think this should matter since I understand the XSL to mean that the anchor tag should match the xml:id of the spanTo on the anchor.

**Comment by awisnicki** [comment]
OK, I think I resolved the last issue with the variable tooltip title on anchor. Sync the files and see what you think. If all looks good, then close this issue.

**Comment by justindlivingstone** [comment]
This looks resolved to me! Absolutely brilliant. Thanks for all your help. I'll close the thread!
