### ISSUE TITLE
Transcribe Stray MT Leaves

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/Missionary-Travels#21]
Please transcribe and encode the stray leaves from DLC (1 page) and NLS (1 page). I've put the images in a folder called "Stray-MT-Leaves." The two images are:

liv_003233_0001.tif
liv_003234_0001.tif

Each of these should go in its own TEI file.

**Comment by kilmunbooks** [comment]
I'll take this. (Complete by 30/10/17)

**Comment by awisnicki** [comment]
Reopening: Has this been proofed by Justin. Also did you update the file names as per my other ticket about that?

**Comment by justindlivingstone** [comment]
No, it hasn't been proofed yet. I have just renamed the tiffs though, and will proof soon.

**Comment by awisnicki** [comment]
Be sure to change file names in transcriptions also.

**Comment by justindlivingstone** [comment]
I've now proofed the xml and conversion, added the glossary ids, and uploaded to MT-Manuscript-archival github folder.

**Comment by awisnicki** [comment]
I've update the MT plan to take account of this plus noted when I will review and you will finalize.
