### ISSUE TITLE
Transcribe Suppressed Preface from MT

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/Missionary-Travels#22]
Please transcribe and encode the suppressed preface from MT (3 pages): http://livingstoneonline.org/islandora/search/preface?view_pid=liv%3A003010&view_page=0

**Comment by kilmunbooks** [comment]
I'll take this. (Complete by 30/10/17)

**Comment by awisnicki** [comment]
Reopening: Has this been proofed by Justin. Also did you update the file names as per my other ticket about that?

**Comment by justindlivingstone** [comment]
I haven't proofed this yet. Did you want the suppressed preface to be given a new file name as well? Or are you just referring to the other stray leaves? Kate has transcribed the suppressed preface using the id liv_003010.

**Comment by awisnicki** [comment]
No, suppressed preface is already in the system under it's existing file name, so you use that.

**Comment by justindlivingstone** [comment]
I've now proofed the xml and conversion, added the glossary ids, and uploaded to MT-Manuscript-archival github folder.

**Comment by awisnicki** [comment]
I've update the MT plan to take account of this plus noted when I will review and you will finalize.
