### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/Missionary-Travels#23]
The two MT fragments can be renamed liv_000103 and liv_000104, could one of you please do that, then post the updated files to our sever in your shared folder (and let us know you did it).

**Comment by awisnicki** [comment]
Please update the numbering as soon as you can, as I'd like to publish these images.

**Comment by justindlivingstone** [comment]
I've just renamed these and replaced the files on agnes. They're in the 'Stray-MT-Pages' subfolder.

**Comment by awisnicki** [comment]
Perfection instantiated.
