### ISSUE TITLE
Retracing metamarks

### ISSUE THREAD

**Issue by justindlivingstone** [livingstoneonline/Missionary-Travels#3]
I've noticed that when <retrace> is used over an empty metamark (i.e. when an editor retraces the arrow for 'insertion'), the metamark doesn't appear. For instance, in the line below, the arrow isn't appearing at all, even when I remove the code you added to the xsl to turn off empty metamarks:

<retrace hand="#U3" rend="red"><metamark function="insertion" rend="gray" resp="#U2"/></retrace>

A related issue is that in such cases, <retrace> is not being turned off by the closing tag. Instead, it is staying on until the end of the paragraph. For a particularly noticeable example, see 0114 (line 946 in the xml), where the retrace in red stays on for the rest of the paragraph (in this case, the next two pages).

**Comment by awisnicki** [comment]
Try defining retrace in the XSLT with a child of metamark: xsl:template match="retrace[child::metamark]"

**Comment by justindlivingstone** [comment]
Managed to sort this out. When I turned empty metamarks back on and adjusted the priorities, <retrace> started to function properly again. I also tinkered with the css to ensure that the colours were working properly with <retrace>.

**Comment by awisnicki** [comment]
Also brilliant!
