### ISSUE TITLE
addSpan

### ISSUE THREAD

**Issue by justindlivingstone** [livingstoneonline/Missionary-Travels#6]
Hi Adrian,

If you resync github, I've uploaded a file called 'addSpan tests' and a couple of jpegs. 

As we discussed yesterday, I can't get addSpan to work across paragraphs. If you look at page 0185 in the xml file, alongside the jpg of 0185 you'll see the problem. The two paragraphs in this page are added by Livingstone (within a div by Charles) and so should both be in DL's hand. 

As you can see, it currently isn't working because the second paragraph reverts in appearance to that of Charles. I've tried several approaches (i.e. including `spanTo` in the `addSpan` template in xslt, and messing around with various things in a new `anchor` template) but had no luck.

Could you take a look? I suspect that as well as sorting out the `anchor` template, `addSpan` needs to recognise a child/descendant of `p`.

**Comment by awisnicki** [comment]
Is this sorted out? Can we close this?

**Comment by justindlivingstone** [comment]
Yes, this is sorted out. I added a hand to `p` instead, which resolved it. I'll close it now.
