### ISSUE TITLE
Marginal metamark deletions

### ISSUE THREAD

**Issue by justindlivingstone** [livingstoneonline/Missionary-Travels#8]
Hi Adrian,

As I proof the MT conversion, I've come across one small recurring issue. When a metamark floating in the margin is deleted, the strikethrough is not showing.

Resync github to see a test file I've uploaded, 'Metamark deletion tests', which gives a number of examples. As you can see, when the metamark forms part of a note floating in the margin, the deletion works fine. Equally, when metamarks are not floating but are instead in the body of the text, the deletion also works. It's only an issue with metamarks floating in the margin on their own. Any ideas?

**Comment by awisnicki** [comment]
Resync. Resolved for the latter two issues in the file, but not for that big slash. Is that slash also supposed to have a line through? I'm not sure why the other two are working but not the big slash.

**Comment by justindlivingstone** [comment]
Thanks Adrian. The problem with this solution is that it doesn't recognise deletions in different colours. So when a value of `rend="red"` is added to `del`, the deletion doesn't appear at all. It turns out this is the problem with the big slash. If you take away the `rend` value, the deletion will appear.

The solution for this problem needs to accommodate the colour variations that we currently have for `del`, for which there are instructions in xsl (i.e. red line through black word; black line through red word; gray through red, and so on). I wonder if we need a template for `metamark` with a parent/ancestor of `del`? Or should we try to do it through css?

 It's strange that the problem only appears when the metamarks are in the margin.

**Comment by awisnicki** [comment]
Closing this since it appears resolved.
